# 화이트리스트 설정
[whitelist]
allowed_users = [
    { name = "김춘식" },
    { name = "신명석" },
    { name = "테스트사용자" },
    { name = "admin" }
]

# 개발 모드 설정 (개발 환경: true, 운영 환경: false)
dev_mode = true

# API 설정 (이미 다른 곳에서 관리 중이라 주석 처리)
# [api]
# key = "4c7c5bbc44eccc1e9fcf666e6c4a43cd:10000:7dc198e432c782642629d1fa5f6c398f04cdd4ea"
# url = "https://ability-worker.agentria.io/api/ability"
# 
# [api.endpoints]
# chat = "student-counseling-chat-session"
# summary = "session-summary-and-save"
# report = "session-report-generator"
